
package sis_fac_restaurante;

//Todos los menus del restaurante se van a encontrar dentro de esta clase para ser desplegados en el formulario Ingresar_Pedido
public class Menus {

    //El menu menuEntero va a contener todos los productos del restaurante, va a ser el que se va a utilizar interna y logicamente en el programa
    public String [][] menuEntero = {{"t", "1", "Gallopinto con huevo", "3000"}, 
                                     {"t", "2", "Olla de Carne", "5000"},
                                     {"t", "3", "Tortilla con Queso", "2500"},
                                     {"t", "4", "Chifrijo", "3500"},
                                     {"t", "5", "Vigoron", "3500"},
                                     {"t", "6", "Sopa Negra", "3000"},
                                     {"t", "7", "Platano con Queso", "2700"},
                                     {"t", "8", "Arroz con Pollo", "4000"},
                                     {"r", "9", "Hamburguesa de queso con papas", "3500"}, 
                                     {"r", "10", "Perros calientes", "1500"},
                                     {"r", "11", "Nuggets", "2500"},
                                     {"r", "12", "Papas supremas", "3500"},
                                     {"r", "13", "Burritos", "2500"},
                                     {"r", "14", "Dedos de queso", "2000"},
                                     {"r", "15", "Alitas", "5000"},
                                     {"r", "16", "Fajitas de Pollo", "4000"},
                                     {"r", "17", "Tacos de Birria", "6000"},
                                     {"r", "18", "Pizza Jamon y Queso", "4000"},
                                     {"v", "19", "Sopa de tomate", "2000"}, 
                                     {"v", "20", "Arroz con Verduras cocidas", "3500"},
                                     {"v", "21", "Mac and cheese", "3000"},
                                     {"v", "22", "Hummus", "3500"},
                                     {"v", "23", "Ensalada verde", "1500"},
                                     {"v", "24", "Sopa de frijol", "2000"},
                                     {"v", "25", "Sopa de cebolla", "2000"},
                                     {"v", "26", "Papas Bravas", "4000"},
                                     {"v", "27", "Ensalada de Garbanzos", "3500"},
                                     {"l", "28", "Cerveza", "1500"}, 
                                     {"l", "29", "Mojito", "2000"},
                                     {"l", "30", "Piña colada", "2000"},
                                     {"l", "31", "Taikiri", "2500"},
                                     {"l", "32", "Botella de Vino", "12500"},
                                     {"l", "33", "Vodka", "6000"},
                                     {"l", "34", "Margarita", "3000"},
                                     {"l", "35", "Sangria", "4000"},
                                     {"l", "36", "Bloody Mary", "4000"},
                                     {"l", "37", "Botella Cacique", "8000"},
                                     {"n", "38", "Fresco de Frutas", "2000"}, 
                                     {"n", "39", "Fresco de Piña", "2000"},
                                     {"n", "40", "Fresco de Sandia", "2000"},
                                     {"n", "41", "Fresco de Fresa", "2000"},
                                     {"n", "42", "Fresco de Mango", "2000"},
                                     {"n", "43", "Fresco de Melon", "2000"},
                                     {"n", "44", "Fresco de Guanabana", "2000"},
                                     {"n", "45", "Hierba Buena", "3000"},
                                     {"n", "46", "Fresco de Mora", "2500"},
                                     {"g", "47", "Ginger Ale", "1800"}, 
                                     {"g", "48", "CocaCola", "1800"},
                                     {"g", "49", "Fresca", "2000"},
                                     {"g", "50", "7 UP", "2000"},
                                     {"g", "51", "Sarsa", "2000"},
                                     {"g", "52", "Fanta de Uva", "2000"},
                                     {"g", "53", "Fanta Naraja", "2000"},
                                     {"g", "54", "Fanta Roja", "2000"},
                                     {"g", "55", "Inka Cola", "3000"}};
}
